# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mampf.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mampf.proto", :syntax => :proto3) do
    add_message "mampf.Course" do
      optional :id, :int32, 1
      optional :title, :string, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
      optional :updated_at, :message, 4, "google.protobuf.Timestamp"
      optional :short_title, :string, 5
      optional :organizational, :bool, 6
      optional :organizational_concept, :string, 7
      optional :locale, :string, 8
      optional :term_independent, :bool, 9
      optional :image_data, :string, 10
    end
    add_message "mampf.Lecture" do
      optional :id, :int32, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      optional :updated_at, :message, 3, "google.protobuf.Timestamp"
      optional :course_id, :int32, 4
      optional :term_id, :int32, 5
      optional :teacher_id, :int32, 6
      optional :start_chapter, :int32, 7
      optional :absolute_numbering, :bool, 8
      optional :start_section, :int32, 9
      optional :organizational_concept, :string, 10
      optional :organizational, :bool, 11
      optional :muesli, :bool, 12
      optional :released, :string, 13
      optional :content_mode, :string, 14
      optional :passphrase, :string, 15
      optional :locale, :string, 16
      optional :sort, :string, 17
      optional :forum_id, :int32, 18
      optional :structure_ids, :string, 19
      optional :comments_disabled, :bool, 20
      optional :organizational_on_top, :bool, 21
      optional :disable_teacher_display, :bool, 22
    end
    add_message "mampf.User" do
      optional :id, :int32, 1
      optional :email, :int32, 2
      optional :admin, :bool, 3
      optional :name, :string, 4
    end
    add_message "mampf.Term" do
      optional :id, :int32, 1
      optional :year, :int32, 2
      optional :season, :string, 3
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      optional :updated_at, :message, 5, "google.protobuf.Timestamp"
      optional :active, :bool, 6
    end
    add_message "mampf.LecturesQueryResult" do
      repeated :lectures, :message, 1, "mampf.Lecture"
    end
    add_message "mampf.LecturesByUserRequest" do
      optional :user_id, :int32, 1
    end
    add_message "mampf.TermRequest" do
      optional :term_id, :int32, 1
    end
    add_message "mampf.TermsRequest" do
      optional :user_id, :int32, 1
    end
    add_message "mampf.TermsRequestResult" do
      repeated :terms, :message, 1, "mampf.Term"
    end
    add_message "mampf.LoginInformation" do
      optional :email, :string, 1
      optional :password, :string, 2
    end
    add_message "mampf.LoginResult" do
      optional :success, :bool, 1
      optional :user, :message, 2, "mampf.User"
    end
    add_message "mampf.UserLookUp" do
      optional :id, :int32, 1
    end
  end
end

module Mampf
  Course = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.Course").msgclass
  Lecture = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.Lecture").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.User").msgclass
  Term = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.Term").msgclass
  LecturesQueryResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.LecturesQueryResult").msgclass
  LecturesByUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.LecturesByUserRequest").msgclass
  TermRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.TermRequest").msgclass
  TermsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.TermsRequest").msgclass
  TermsRequestResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.TermsRequestResult").msgclass
  LoginInformation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.LoginInformation").msgclass
  LoginResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.LoginResult").msgclass
  UserLookUp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mampf.UserLookUp").msgclass
end
