# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mampf.proto for package 'mampf'

require 'grpc'
require_relative 'mampf_pb'

module Mampf
  module MaMpfLectureService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mampf.MaMpfLectureService'

      rpc :GetLecturesForUser, ::Mampf::LecturesByUserAndTermRequest, ::Mampf::LecturesQueryResult
      rpc :GetIsEditor, ::Mampf::IsEditorRequest, ::Mampf::IsEditorResponse
    end

    Stub = Service.rpc_stub_class
  end
  module MaMpfTermService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mampf.MaMpfTermService'

      rpc :GetTerm, ::Mampf::TermRequest, ::Mampf::Term
      # returns all Terms for a User, in which they have lectures
      rpc :GetTerms, ::Mampf::TermsRequest, ::Mampf::TermsRequestResult
    end

    Stub = Service.rpc_stub_class
  end
  module MaMpfAuthService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mampf.MaMpfAuthService'

      rpc :Login, ::Mampf::LoginInformation, ::Mampf::LoginResult
      rpc :LookUpUser, ::Mampf::UserLookUp, ::Mampf::User
    end

    Stub = Service.rpc_stub_class
  end
end
